export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'

export const LOADING = 'LOADING'
export const SET_CURRENT_EDITED_SCHEMA_OR_FIELD = 'SET_CURRENT_EDITED_SCHEMA_OR_FIELD'

export const SET_SCHEMA_LIST = 'SET_SCHEMA_LIST'
export const LOADING_SCHEMAS = 'LOADING_SCHEMAS'
export const DELETE_SCHEMA = 'DELETE_SCHEMA'
export const CREATE_SCHEMA = 'CREATE_SCHEMA'

export const LOADING_CONTENT = 'LOADING_CONTENT'
export const SET_CURRENT_CONTENT_VALUES = 'SET_CURRENT_CONTENT_VALUES'
export const SET_DEFAULT_VALUES = 'SET_DEFAULT_VALUES'
export const RESET_CURRENT_CONTENT_VALUES = 'RESET_CURRENT_CONTENT_VALUES'
export const DELETE_CONTENT = 'DELETE_CONTENT'
export const RESET_CURRENT_CONTENT_LIST = 'RESET_CURRENT_CONTENT_LIST'
export const SET_CURRENT_CONTENT_LIST = 'SET_CURRENT_CONTENT_LIST'
export const SET_ALL_CURRENT_CONTENT_VALUES = 'SET_ALL_CURRENT_CONTENT_VALUES'

export const LOADING_USER = 'LOADING_USER'
export const SET_CURRENT_USER_VALUES = 'SET_CURRENT_USER_VALUES'
export const RESET_CURRENT_USER_VALUES = 'RESET_CURRENT_USER_VALUES'
export const DELETE_USER = 'DELETE_USER'
export const SET_ALL_USERS_COUNT = 'SET_ALL_USERS_COUNT'
export const RESET_CURRENT_USER_LIST = 'RESET_CURRENT_USER_LIST'
export const SET_CURRENT_USER_LIST = 'SET_CURRENT_USER_LIST'
export const SET_ALL_CURRENT_USER_VALUES = 'SET_ALL_CURRENT_USER_VALUES'

export const SET_FIELD_LIST = 'SET_FIELD_LIST'
export const LOADING_FIELDS = 'LOADING_FIELDS'
export const DELETE_FIELD = 'DELETE_FIELD'

export const SET_ALL_ROLES = 'SET_ALL_ROLES'
export const LOADING_ROLES = 'LOADING_ROLES'
export const DELETE_ROLE = 'DELETE_ROLE'
export const SET_CURRENT_ROLE_VALUES = 'SET_CURRENT_ROLE_VALUES'
export const RESET_CURRENT_ROLE_VALUES = 'RESET_CURRENT_ROLE_VALUES'
export const SET_ALL_CURRENT_ROLE_VALUES = 'SET_ALL_CURRENT_ROLE_VALUES'

export const SET_ALL_TRANSLATIONS = 'SET_ALL_TRANSLATIONS'
export const LOADING_TRANSLATIONS = 'LOADING_TRANSLATIONS'

export const ADD_EXTENSION = 'ADD_EXTENSION'
export const SET_ALL_EXTENSIONS = 'SET_ALL_EXTENSIONS'
export const SET_ALL_ACTIVE_DASHBOARD_EXTENSIONS =
  'SET_ALL_ACTIVE_DASHBOARD_EXTENSIONS'
export const LOADING_EXTENSIONS = 'LOADING_EXTENSIONS'
export const LOADING_ACTIVE_DASHBOARD_EXTENSIONS =
  'LOADING_ACTIVE_DASHBOARD_EXTENSIONS'
export const DELETE_EXTENSION = 'DELETE_EXTENSION'
export const UPDATE_EXTENSION = 'UPDATE_EXTENSION'
export const ACTIVATE_EXTENSION_LOADING = 'ACTIVATE_EXTENSION_LOADING'
export const DELETE_EXTENSION_LOADING = 'DELETE_EXTENSION_LOADING'

export const LOADING_CAPABILITIES = 'LOADING_CAPABILITIES'
export const DELETE_CAPABILITY = 'DELETE_CAPABILITY'
export const SET_CURRENT_CAPABILITY_VALUES = 'SET_CURRENT_CAPABILITY_VALUES'
export const RESET_CURRENT_CAPABILITY_VALUES = 'RESET_CURRENT_CAPABILITY_VALUES'
export const SET_ALL_CURRENT_CAPABILITY_VALUES =
  'SET_ALL_CURRENT_CAPABILITY_VALUES'
export const SET_ALL_CAPABILITIES = 'SET_ALL_CAPABILITIES'

export const SET_UPLOADS = 'SET_UPLOADS'
export const SET_UPLOADS_LOADING = 'SET_UPLOADS_LOADING'
export const DELETE_UPLOAD = 'DELETE_UPLOAD'
export const ADD_UPLOAD = 'ADD_UPLOAD'
export const SET_SELECTED_UPLOADS = 'SET_SELECTED_UPLOADS'

export const SET_All_OPTIONS = 'SET_All_OPTIONS'
export const SET_LOGIN_OPTIONS = 'SET_LOGIN_OPTIONS'
export const UPDATE_OPTIONS = 'UPDATE_OPTIONS'
export const RESET_OPTIONS = 'RESET_OPTIONS'
export const LOADING_OPTIONS = 'LOADING_OPTIONS'
export const LOADING_ACTIONS = 'LOADING_ACTIONS'

export const SET_FORM_ERRORS = 'SET_FORM_ERRORS'

export const SET_NOTIFICATIONS_LOADING = 'SET_NOTIFICATIONS_LOADING'
export const SET_NOTIFICATIONS_PAGE = 'SET_NOTIFICATIONS_PAGE'
export const SET_NOTIFICATION_STATUS = 'SET_NOTIFICATION_STATUS'
